// Tier B: career sites that need a real browser to enumerate jobs. Each entry
// points at a search results page plus a pattern that identifies a job link.
export const SITES = [
  { id: 'google', company: 'google', label: 'Google (in-house)',
    listUrl: 'https://www.google.com/about/careers/applications/jobs/results?q=senior%20software%20engineer',
    jobLink: /\/about\/careers\/applications\/jobs\/results\/\d+/ },
  // Microsoft moved its board to Eightfold; the old jobs.careers.microsoft.com
  // search URL redirects there, so match the apply host's job links directly.
  { id: 'microsoft', company: 'microsoft', label: 'Microsoft (in-house)',
    listUrl: 'https://apply.careers.microsoft.com/careers?query=senior%20software%20engineer',
    jobLink: /apply\.careers\.microsoft\.com\/careers\/job\/\d+/ },
  { id: 'apple', company: 'apple', label: 'Apple (in-house)',
    listUrl: 'https://jobs.apple.com/en-us/search?search=senior%20software%20engineer',
    jobLink: /\/en-us\/details\/\d+/ },
  { id: 'meta', company: 'meta', label: 'Meta (in-house)',
    listUrl: 'https://www.metacareers.com/jobs?q=senior%20software%20engineer',
    jobLink: /metacareers\.com\/(jobs|profile\/job_details)\/\d+/ },
  { id: 'tesla', company: 'tesla', label: 'Tesla (in-house)',
    listUrl: 'https://www.tesla.com/careers/search/?query=software%20engineer&site=US',
    jobLink: /\/careers\/search\/job\/\d+/ },
  { id: 'ibm', company: 'ibm', label: 'IBM (in-house)',
    listUrl: 'https://www.ibm.com/careers/search?field_keyword_08[0]=Software%20Engineering',
    jobLink: /careers\.ibm\.com\/(en_US\/careers\/)?JobDetail\?jobId=\d+/i },
  { id: 'cisco', company: 'cisco', label: 'Cisco (in-house)',
    listUrl: 'https://careers.cisco.com/global/en/search-results?keywords=senior%20software%20engineer',
    jobLink: /careers\.cisco\.com\/global\/en\/job\/\d+|jobs\.cisco\.com\/jobs\/ProjectDetail/ },
  { id: 'sap', company: 'sap', label: 'SAP (SuccessFactors)',
    listUrl: 'https://jobs.sap.com/search/?q=senior+software+engineer',
    jobLink: /\/job\/[^"']*?\/\d+\/?$/ },
  { id: 'oracle', company: 'oracle', label: 'Oracle Recruiting Cloud',
    listUrl: 'https://careers.oracle.com/jobs/#en/sites/jobsearch/jobs?keyword=software%20engineer',
    jobLink: /\/job\/\d+|requisitions\?/ },
  { id: 'janestreet', company: 'janestreet', label: 'Jane Street (in-house)',
    listUrl: 'https://www.janestreet.com/join-jane-street/open-roles/?type=experienced-candidates',
    jobLink: /\/join-jane-street\/position\/\d+/ },
  { id: 'bloomberg', company: 'bloomberg', label: 'Bloomberg (in-house)',
    listUrl: 'https://careers.bloomberg.com/job/search?q=senior+software+engineer',
    jobLink: /\/job\/detail\/\d+/ },
  { id: 'goldman', company: 'goldmansachs', label: 'Goldman Sachs (in-house)',
    listUrl: 'https://higher.gs.com/results?page=1&sort=RELEVANCE&search=software%20engineer',
    jobLink: /\/roles\/\d+|\/results\/\w+/ },
  { id: 'uber', company: 'uber', label: 'Uber (in-house)',
    listUrl: 'https://jobs.uber.com/en/jobs/?query=senior%20software%20engineer',
    jobLink: /jobs\.uber\.com\/en\/jobs\/\d+/ },
  { id: 'stripe', company: 'stripe', label: 'Stripe (in-house)',
    listUrl: 'https://stripe.com/careers/search?q=engineer',
    jobLink: /stripe\.com\/careers\/listing\/[\w-]+\/\d+/ },
  { id: 'spotify', company: 'spotify', label: 'Spotify (in-house)',
    listUrl: 'https://www.lifeatspotify.com/jobs?q=engineer',
    jobLink: /\/jobs\/[\w-]+/ },
  { id: 'atlassian', company: 'atlassian', label: 'Atlassian (in-house)',
    listUrl: 'https://www.atlassian.com/company/careers/all-jobs?search=senior%20software%20engineer',
    jobLink: /\/careers\/details\/[\w-]+/ },
  { id: 'snap', company: 'snap', label: 'Snap (in-house)',
    listUrl: 'https://careers.snap.com/jobs?search=software%20engineer',
    jobLink: /careers\.snap\.com\/job\?id=/ },
  { id: 'workatastartup', company: 'ycombinator', label: 'Y Combinator Work at a Startup',
    listUrl: 'https://www.workatastartup.com/jobs?role=eng&sortBy=keyword&hasEquity=any&hasSalary=any',
    jobLink: /\/jobs\/\d+/ },
  { id: 'amazon', company: 'amazon', label: 'Amazon (in-house)',
    listUrl: 'https://www.amazon.jobs/en/search?base_query=senior+software+development+engineer',
    jobLink: /\/en\/jobs\/\d+/ },
  { id: 'netflix', company: 'netflix', label: 'Netflix (Eightfold)',
    listUrl: 'https://explore.jobs.netflix.net/careers?query=senior%20software%20engineer',
    jobLink: /pid=\d+/ },
  { id: 'nasa', company: 'usajobs', label: 'USAJOBS (federal)',
    listUrl: 'https://www.usajobs.gov/Search/Results?k=software%20engineer&hp=public',
    jobLink: /\/job\/\d+/ },
  { id: 'wellfound', company: 'wellfound', label: 'Wellfound (AngelList)',
    listUrl: 'https://wellfound.com/role/r/senior-software-engineer',
    jobLink: /\/jobs\/\d+/ },
// Second wave: large employers on platforms we have not sampled yet.
  { id: 'pinterest', company: 'pinterest', label: 'Pinterest careers',
    listUrl: 'https://www.pinterestcareers.com/jobs/?search=software+engineer',
    jobLink: /pinterestcareers\.com\/(en\/)?job(s)?\/[\w-]+/ },
  { id: 'nike', company: 'nike', label: 'Nike careers',
    listUrl: 'https://careers.nike.com/search-jobs/software%20engineer',
    jobLink: /careers\.nike\.com\/[\w-]+\/job\/[\w-]+/ },
  { id: 'comcast', company: 'comcast', label: 'Comcast careers',
    listUrl: 'https://jobs.comcast.com/jobs?keyword=software%20engineer',
    jobLink: /jobs\.comcast\.com\/job\/|\/jobs\/\d+/ },
  { id: 'lockheed', company: 'lockheedmartin', label: 'Lockheed Martin careers',
    listUrl: 'https://www.lockheedmartinjobs.com/search-jobs/software%20engineer',
    jobLink: /lockheedmartinjobs\.com\/job\/[\w-]+/ },
  { id: 'boeing', company: 'boeing', label: 'Boeing careers',
    listUrl: 'https://jobs.boeing.com/search-jobs/software%20engineer',
    jobLink: /jobs\.boeing\.com\/job\/[\w-]+/ },
  { id: 'rtx', company: 'rtx', label: 'RTX careers',
    listUrl: 'https://careers.rtx.com/global/en/search-results?keywords=software%20engineer',
    jobLink: /careers\.rtx\.com\/global\/en\/job\/[\w-]+/ },
  { id: 'accenture', company: 'accenture', label: 'Accenture careers',
    listUrl: 'https://www.accenture.com/us-en/careers/jobsearch?jk=software%20engineer',
    jobLink: /accenture\.com\/us-en\/careers\/jobdetails\?id=/i },
  { id: 'deloitte', company: 'deloitte', label: 'Deloitte careers',
    listUrl: 'https://apply.deloitte.com/careers/SearchJobs/software%20engineer',
    jobLink: /apply\.deloitte\.com\/careers\/JobDetail\/[\w-]+/i },
  { id: 'ge', company: 'gecareers', label: 'GE careers',
    listUrl: 'https://jobs.gecareers.com/global/en/search-results?keywords=software%20engineer',
    jobLink: /gecareers\.com\/global\/en\/job\/[\w-]+/ },
  { id: 'shopify', company: 'shopify', label: 'Shopify careers',
    listUrl: 'https://www.shopify.com/careers/search?keywords=engineer',
    jobLink: /shopify\.com\/careers\/[\w-]+/ },
  { id: 'deshaw', company: 'deshaw', label: 'D. E. Shaw (in-house)',
    listUrl: 'https://www.deshaw.com/careers/choose-your-path',
    jobLink: /deshaw\.com\/careers\/[\w-]+-\d+/ },
  { id: 'sig', company: 'sig', label: 'Susquehanna (SIG) careers',
    listUrl: 'https://careers.sig.com/search-jobs/software',
    jobLink: /careers\.sig\.com\/job\/[\w-]+/ },
  { id: 'imc', company: 'imc', label: 'IMC Trading careers',
    listUrl: 'https://careers.imc.com/us/en/search-results?keywords=software',
    jobLink: /careers\.imc\.com\/us\/en\/job\/[\w-]+/ },
  { id: 'optiver', company: 'optiver', label: 'Optiver careers',
    listUrl: 'https://optiver.com/working-at-optiver/career-opportunities/?search=engineer',
    jobLink: /optiver\.com\/working-at-optiver\/career-opportunities\/[\w-]+/ },
];
