// Known board slugs per ATS. These are guesses against public board APIs --
// misses simply return nothing, so breadth costs little.
export const GREENHOUSE_TENANTS = [
  'anthropic','stripe','databricks','airbnb','figma','discord','robinhood','coinbase','cloudflare',
  'datadog','twilio','instacart','gitlab','doordash','reddit','duolingo','asana','benchling','plaid',
  'brexhq','retool','scaleai','samsara','affirm','dropbox','lyft','unity','gusto','airtable','amplitude',
  'hashicorp','mongodb','elastic','confluent','snyk','sentry','vercel','spacex','citadel','twosigma',
  'hudsonrivertrading','jumptrading','wise','klaviyo','grammarly','chainalysis','flexport','nuro',
  'zipline','astranis','applieddintuition','lucidmotors','faire','ramp','sourcegraph','temporal',
  'anduril','sofi','carta','rippling','gong','loom','miro','calendly','webflow','zapier','segment',
  'okta','auth0','duosecurity','crowdstrike','tanium','netskope','abnormalsecurity','wiz','orca',
  'sumologic','splunk','newrelic','pagerduty','launchdarkly','circleci','buildkite','netlify',
  'planetscale','cockroachlabs','neo4j','couchbase','redis','timescale','starburst','dremio',
  'fivetran','dbtlabs','montecarlodata','hex','sigmacomputing','census','hightouch','airbyte',
  'astronomer','prefect','dagster','weaviate','pinecone','chroma','langchain','huggingface',
  'scale','labelbox','snorkelai','runwayml','stabilityai','adept','character','imbue','magic',
  'cresta','abridge','tempus','flatiron','oscarhealth','devoted','rohealth','hims','noom','calm',
  'headspace','whoop','oura','peloton','strava','allbirds','warbyparker','glossier','away',
  'chime','current','varomoney','marqeta','modernTreasury','unit','lithic','alloy','persona',
  'checkr','deel','remote','oysterhr','papayaglobal','velocityglobal','rippling2','justworks',
  'betterup','lattice','culture-amp','15five','guild','coursera','udemy','skillshare','masterclass',
  'chegg','quizlet','photomath','codecademy','datacamp','pluralsight','educative','exercism',
  'twitch','patreon','substack','ghost','medium','bufferapp','hootsuite','sproutsocial','later',
  'shipbob','shippo','easypost','project44','flexe','stord','ryder','convoy','loadsmart',
  'opendoor','compass','divvyhomes','pacaso','roofstock','landis','hippo','kin','root','lemonade',
  'nerdwallet','creditkarma','sofi2','betterment','wealthfront','public','stash','acorns','m1finance',
  'alpaca','tradingview','polygonio','kalshi','polymarket','gemini','krakenfx','blockchain','ripple',
  'circle','fireblocks','anchorage','paxos','bitgo','ledger','magiceden','opensea','uniswaporg',

  // Second wave of Greenhouse boards: more mid/large tech employers.
  'sigmacomputing','instabase','arize','galileo','truera','fiddler','robustintelligence',
  'verkada','flockSafety','motive','samsara2','nauto','netradyne','kodiak','aurora','waabi',
  'gatik','einride','bearrobotics','serverobotics','starship','skydio','shield','saronic',
  'castelion','hermeus','stoke','relativity','firefly','rocketlab','planet','spire','iceye',
  'muonspace','varda','impulse','k2space','turion','albedo','slingshot','trueanomaly',
  'kla','onto','nvidia2','groq','cerebras','sambanova','tenstorrent','etched','positron',
  'lightmatter','ayar','celestial','xscape','psiquantum','quantinuum','ionq','rigetti',
  'atomcomputing','quera','infleqtion','pasqal','alice-bob','nord-quantique',
  'stord2','flowspace','deliverr','shipmonk','cart','bolt','fastspring','paddle','lemonsqueezy',
  'chargebee','recurly','maxio','metronome','orb','lago','stigg','schematic',
  'workos','clerk','stytch','descope','frontegg','propelauth','kinde','logto',
  'unstructured','llamaindex','crewai','langfuse','braintrust','humanloop','freeplay',
  'galileo2','patronus','guardrails','protectai','lakera','promptarmor','hiddenlayer',
  'trailofbits','nccgroup','bishopfox','praetorian','coalfire','optiv','mandiant',
  'huntress','arctic-wolf','expel','redcanary','dragos','claroty','armis','ordr',
  'axonius','jupiterone','panther','matano','runreveal','scanner','observe','cribl',
  'grafana','chronosphere','honeycomb','lightstep','signoz','highlight','posthog',
  'june','amplitude2','heap','fullstory','logrocket','smartlook','contentsquare',
  'braze','iterable','onesignal','airship','leanplum','clevertap','moengage',
  'cameo','whatnot','poshmark','depop','vinted','grailed','stockx','goat','ebay2',
  'faire2','ankorstore','mable','abound','creoate','tundra','bulletin',
  'gopuff2','getir','gorillas','flink','zapp','dija','weezy','jokr',
  'sword','hinge-health','omada','virta','vida','lark','livongo','teladoc',
  'included','spring2','modern-health','ginger','talkspace','betterhelp','brightline',
  'maven','carrot','progyny','kindbody','tia','oula','pomelo','midi',
  'komodo','truveta','verily','color','invitae','tempus2','guardant','grail',
  'recursion','insitro','isomorphic','genesis','iambic','chai','cradle','profluent',
  'benchling2','dotmatics','sapio','labguru','scispot','ganymede','tetrascience',
  'formlabs','markforged','desktopmetal','velo3d','divergent','relativity2',
  'zoox','motional','may-mobility','beep','oxa','wayve','helm','ghost-autonomy',
  'ouster','luminar','aeva','innoviz','hesai','cepton','aeye',
];

export const LEVER_TENANTS = [
  'palantir','netflix','quora','anduril','attentive','brave','nubank','wealthsimple','ro','sardine',
  'matchgroup','voleon','kickstarter','shieldai','cohere','plusai','inflection','mistral','tala',
  'pave','eventbrite','handshake','lyra','spring','headway','alto','honor','papa','cityblock',
  'kajabi','podium','olo','toasttab','sweetgreen','wonder','misfitsmarket','imperfectfoods',
  'thumbtack','angi','porch','houzz','yelp','nextdoor','life360','ringdna','aircall','dialpad',
  'clari','outreach','salesloft','gong2','chorus','avoma','fathom','otter','rev','descript',
  'veho','gopuff','instawork','wonolo','jobber','servicetitan','housecallpro','workiz','skedulo',
  'clipboardhealth','trusted','incredible','vivian','nomadhealth','medely',' shiftkey','connectrn',
  'sentilink','socure','veriff','sumsub','onfido','trulioo','middesk','mercury2','arc','pilot',
  'ledgy','pry','runway2','causal','mosaic','abacum','cube','vareto','anaplan','pigment',

  'gem','ashby2','dover','findem','seekout','hiretual','fetcher','moonhub',
  'moveworks','aisera','forethought','ada','ultimate','netomi','yellowai',
  'observeai','level-ai','assembled','regal','replicant','parloa','poly-ai',
  'sanctuary','figure','apptronik','1x','agility','boston-dynamics','anybotics',
  'dexterity','ambi','osaro','covariant','vicarious','plus-one','righthand',
  'formic','path','bright-machines','machina','vention','symbotic','locus',
  'fetch-robotics','6river','geek-plus','exotec','autostore','attabotics',
  'sila','group14','onto2','solid-power','quantumscape','ses','factorial',
  'redwood','li-cycle','ascend','cirba','ecobat','american-battery',
  'commonwealth','helion','tae','zap','general-fusion','type-one','pacific-fusion',
  'xcimer','marathon','realta','avalanche','thea','proxima','focused-energy',
  'terrapower','oklo','xenergy','kairos','natura','deep-fission','aalo','valar',
];

export const ASHBY_TENANTS = [
  'openai','ramp','linear','notion','vanta','deel','mercury','replit','supabase','clickhouse','modal',
  'anysphere','sierra','elevenlabs','perplexity.ai','runway','harvey','together','weights-and-biases',
  'render','watershed','gathertown','baseten','chainguard','browserbase','e2b','fal','cartesia',
  'suno','udio','pika','luma','decagon','glean','writer','typeface','jasper','copy-ai','tome',
  'gamma','beautiful-ai','pitch','coda','craft','mem','reflect','tana','capacities','heptabase',
  'attio','folk','clay','apollo-io','instantly','smartlead','lemlist','warmly','common-room',
  'orbit','commsor','tribe','circle-so','discourse','forem','hashnode','dev-to','bearblog',
  'railway','fly-io','koyeb','porter','northflank','qovery','defang','sst','vercel2','deno',
  'bun','oven','astro','remix','svelte','solid','qwik','nuxt','vuejs','angular',
  'sylvera','patch','watershed2','persefoni','normative','plan-a','greenly','sweep','emitwise',
  'unit21','sardine2','alloy2','sift','forter','signifyd','riskified','ravelin','seon',
  'openphone','loops','resend','knock','courier','novu','postmark','customerio2','plain',

  'cognition','magic-dev','poolside','augment','codeium','tabnine','sourcegraph2',
  'zed','warp','fig','raycast','arc','the-browser-company','sigma','superhuman',
  'shortwave','hey','missive','front','intercom','plain2','pylon','unthread',
  'granola','circleback','spinach','read','supernormal','tldv','grain',
  'synthesia','heygen','hedra','captions','opus','veed','kapwing','descript2',
  'photoroom','picsart','lightricks','facetune','remini','lensa','prisma',
  'midjourney','ideogram','recraft','leonardo','playground','krea','freepik',
  'physical-intelligence','skild','generalist','dyna','mimic','flexion',
  'reflection','thinking-machines','ssi','world-labs','fei-fei','pika2',
  'axiom','turso','xata','nile','neon','prisma2','drizzle','kysely',
  'convex','instantdb','triplit','electric','powersync','zero','rocicorp',
  'val-town','deno2','stackblitz','codesandbox','gitpod','coder','daytona',
  'depot','namespace','blacksmith','warpbuild','buildjet','actuated',
  'trigger','inngest','hatchet','windmill','kestra','temporal2','restate',
  'tigris','wasabi','backblaze','cloudflare2','bunny','fastly2','edgio',
];

export const WORKDAY_TENANTS = [
  ['nvidia.wd5.myworkdayjobs.com','nvidia','NVIDIAExternalCareerSite'],
  ['salesforce.wd12.myworkdayjobs.com','salesforce','External_Career_Site'],
  ['adobe.wd5.myworkdayjobs.com','adobe','external_experienced'],
  ['workday.wd5.myworkdayjobs.com','workday','Workday'],
  ['intel.wd1.myworkdayjobs.com','intel','External'],
  ['paypal.wd1.myworkdayjobs.com','paypal','jobs'],
  ['ebay.wd5.myworkdayjobs.com','ebay','apply'],
  ['intuit.wd1.myworkdayjobs.com','intuit','External'],
  ['capitalone.wd1.myworkdayjobs.com','capitalone','Capital_One'],
  ['walmart.wd5.myworkdayjobs.com','walmart','WalmartExternal'],
  ['dell.wd1.myworkdayjobs.com','dell','External'],
  ['sony.wd1.myworkdayjobs.com','sony','SonyGlobalCareers'],
  ['qualcomm.wd5.myworkdayjobs.com','qualcomm','External'],
  ['unitedhealthgroup.wd1.myworkdayjobs.com','unitedhealthgroup','External'],
  ['cisco.wd1.myworkdayjobs.com','cisco','CiscoCareers'],
  ['vmware.wd1.myworkdayjobs.com','vmware','VMware'],
  ['autodesk.wd1.myworkdayjobs.com','autodesk','Ext'],
  ['servicenow.wd1.myworkdayjobs.com','servicenow','careers'],
  ['hpe.wd5.myworkdayjobs.com','hpe','Jobsathpe'],
  ['hp.wd5.myworkdayjobs.com','hp','ExternalCareerSite'],
  ['ibm.wd5.myworkdayjobs.com','ibm','IBM_Careers'],
  ['nike.wd1.myworkdayjobs.com','nike','nike'],
  ['target.wd5.myworkdayjobs.com','target','targetcareers'],
  ['cvshealth.wd1.myworkdayjobs.com','cvshealth','CVS_Health_Careers'],
  ['gm.wd5.myworkdayjobs.com','gm','Careers_GM'],
  ['ford.wd1.myworkdayjobs.com','ford','FordCareers'],
  ['tmobile.wd1.myworkdayjobs.com','tmobile','External'],
  ['comcast.wd5.myworkdayjobs.com','comcast','Comcast_Careers'],
  ['disney.wd5.myworkdayjobs.com','disney','disneycareer'],
  ['warnerbros.wd5.myworkdayjobs.com','warnerbros','global'],
  ['mastercard.wd1.myworkdayjobs.com','mastercard','CorporateCareers'],
  ['visa.wd1.myworkdayjobs.com','visa','Jobs'],
  ['fidelity.wd1.myworkdayjobs.com','fidelity','FidelityCareers'],
  ['blackrock.wd1.myworkdayjobs.com','blackrock','BlackRock_Professional'],
  ['morganstanley.wd5.myworkdayjobs.com','morganstanley','External'],
  ['jpmc.wd5.myworkdayjobs.com','jpmc','jpmc'],
  ['amex.wd1.myworkdayjobs.com','amex','aexp_external'],
  ['boeing.wd1.myworkdayjobs.com','boeing','EXTERNAL_CAREERS'],
  ['northropgrumman.wd1.myworkdayjobs.com','northropgrumman','Northrop_Grumman_External_Site'],
  ['pfizer.wd1.myworkdayjobs.com','pfizer','PfizerCareers'],
  ['merck.wd5.myworkdayjobs.com','merck','SearchJobs'],
  ['amgen.wd1.myworkdayjobs.com','amgen','Amgen_Careers'],
  ['siemens.wd1.myworkdayjobs.com','siemens','SGRE'],
  ['philips.wd3.myworkdayjobs.com','philips','jobs-and-careers'],
  ['unilever.wd3.myworkdayjobs.com','unilever','Unilever_Careers'],
  ['nestle.wd3.myworkdayjobs.com','nestle','nestle'],
  ['pepsico.wd3.myworkdayjobs.com','pepsico','PepsiCoCareers'],
  ['kroger.wd5.myworkdayjobs.com','kroger','ExternalKrogerCareers'],
  ['lowes.wd5.myworkdayjobs.com','lowes','lowes'],
  ['bestbuy.wd5.myworkdayjobs.com','bestbuy','BBYExternal'],
];

export const SMARTRECRUITERS_TENANTS = [
  'Visa','Ubisoft','BoschGroup','Squarespace','McDonalds','IKEA','Biogen','Avery','Bosch',
  'PublicisGroupe','Equinox','WPPCorporate','Novartis','LinkedIn','Vodafone','Bayer','Kraft',
];

export const WORKABLE_TENANTS = [
  'deliveryhero','kaizengaming','blueground','e-satisfaction','persado','workable','viva-wallet',
  'beat','skroutz','plum','spotawheel','orfium','pollfish','hellasdirect','instashop',
];

export const RECRUITEE_TENANTS = ['scoutbee','framer','mollie','catawiki','bunq','tiqets','otrium','picnic','messagebird'];

export const ASHBY_EXTRA = [];
