// Controlled employer contracts. Only this server's exact fixture origin may use
// these boundaries; data attributes on external pages never grant capabilities.
export const fixtureNames = [
  "greenhouse",
  "lever",
  "ashby",
  "workday",
  "phenom",
];
export function fixturePage(name) {
  return `<!doctype html><html><head><meta charset="utf-8"><title>${name} fixture</title><style>body{font:18px system-ui;max-width:760px;margin:40px auto;padding:20px}label,fieldset{display:block;margin:20px 0}input,select,textarea,button{font:inherit;padding:10px}button{margin:8px} [hidden]{display:none!important}</style></head><body><h1>Senior Software Engineer</h1><h2>Fixture ${name}</h2><p>Controlled local employer. No real application.</p><main id="app"></main><script>
const employer=${JSON.stringify(name)}, values={}, app=document.querySelector('#app');let step=1;const max=['workday','phenom'].includes(employer)?6:employer==='ashby'?3:2;
function save(){document.querySelectorAll('[name]').forEach(e=>{if(e.type==='radio'){if(e.checked)values[e.name]=e.value;}else if(e.type==='checkbox')values[e.name]=e.checked;else if(e.type==='file')values[e.name]=Array.from(e.files).map(f=>f.name).join(',');else values[e.name]=e.value;});document.querySelectorAll('[role=radiogroup]').forEach(e=>values[e.id]=e.querySelector('[aria-checked=true]')?.textContent||'');}
function render(){app.dataset.step=String(step);app.dataset.job=employer;app.dataset.final=String(step===max);app.innerHTML='<h3>Step '+step+' of '+max+'</h3>';
if(step===1){app.innerHTML+='<form><label>Full name<input name="fullName" autocomplete="name" required></label><label>Email<input name="email" type="email" required></label><label>Country<select name="country" required><option value="">Choose</option><option>Canada</option><option>United States of America</option></select></label><label>Phone country code<select name="phoneCode"><option value="">Choose</option><option>+1</option><option>+44</option></select></label><label>Phone<input name="phone" type="tel"></label><label>Résumé<input name="resume" type="file" accept=".pdf,.txt"></label>'+(employer==='greenhouse'?'<label>Why this role?<textarea name="motivation" required></textarea></label>':'')+(employer==='lever'?'<fieldset><legend>Available for an interview?</legend><label><input type="radio" name="interview" value="Yes" required>Yes</label><label><input type="radio" name="interview" value="No">No</label></fieldset>':'')+(employer==='ashby'?'<fieldset><legend>Do you need accommodation?</legend><div role="radiogroup" id="accommodation" aria-label="Do you need accommodation?" aria-required="true"><button type="button" role="radio" aria-checked="false">Yes</button><button type="button" role="radio" aria-checked="false">No</button></div><div id="conditional"></div></fieldset>':'')+'<button type="button" data-action="advance">Continue</button></form>';
app.querySelectorAll('[role=radio]').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.setAttribute('aria-checked',String(x===b)));document.querySelector('#conditional').innerHTML=b.textContent==='Yes'?'<label>Accommodation details<textarea name="accommodationDetails" required></textarea></label>':'';});
} else if(step<max){app.innerHTML+='<form><label>City<input name="city" role="combobox" aria-controls="cities" aria-expanded="false" autocomplete="off" required></label><div id="cities" role="listbox"></div><label>Available date<input name="available" type="date" required></label><fieldset><legend>Work history</legend><div id="history"><label>Employer 1<input name="employer1" required></label></div><button type="button" data-action="add-history">Add employer</button></fieldset><button type="button" data-action="advance">Continue</button></form>';const city=app.querySelector('[name=city]');city.oninput=()=>{city.dataset.committed='';setTimeout(()=>{document.querySelector('#cities').innerHTML='<button role="option" type="button">San Francisco</button><button role="option" type="button">New York</button>';city.setAttribute('aria-expanded','true');document.querySelectorAll('[role=option]').forEach(b=>b.onclick=()=>{city.value=b.textContent;city.dataset.committed=b.textContent;city.setAttribute('aria-expanded','false');document.querySelector('#cities').innerHTML='';});},100);};app.querySelector('[data-action=add-history]').onclick=()=>{document.querySelector('#history').insertAdjacentHTML('beforeend','<label>Employer 2<input name="employer2" required></label>');};
} else {app.innerHTML+='<h3>Review application</h3><pre id="values"></pre><label><input name="attestation" type="checkbox" required>I confirm these answers are accurate</label><button type="button" data-action="final">Submit application</button>';document.querySelector('#values').textContent=JSON.stringify(values,null,2);app.querySelector('[data-action=final]').onclick=async()=>{save();if(!values.attestation){alert('Confirm accuracy');return;}const response=await fetch('/receipt/'+employer,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});const receipt=await response.json();app.innerHTML='<h2>Application received</h2><p data-receipt="'+receipt.id+'">Receipt '+receipt.id+'</p>';};}
const next=app.querySelector('[data-action=advance]');if(next)next.onclick=()=>{const form=app.querySelector('form');if(!form.reportValidity())return;const group=app.querySelector('[role=radiogroup]');if(group&&!group.querySelector('[aria-checked=true]'))return;const combo=app.querySelector('[role=combobox]');if(combo&&!combo.dataset.committed)return;save();step++;render();};
}
render();document.addEventListener('submit',e=>e.preventDefault());</script></body></html>`;
}
